#!/bin/bash

if [[ $1 == "clean" ]]; then
    cd ../src;
    /usr/lib/x86_64-linux-gnu/qt5/bin/qmake MachineLearning.pro
    make clean;
    make;
    cd ../tests;
    make clean;
    make;
else
    cd ../src;make;cd ../tests;make;
fi;
